config draft
a5lab/axion pull request #286
Opened 2023-02-16 20:55 UTC by cherokee94

@arufanov 

1. Any certain configs we need to mention?
2. Maybe some examples on ExecStart with descriptions?

2023-02-16 21:54 UTC, arufanov commented
@cherokee94 
see my last commit. It has some minor fixes. I hope you are agree with it.

2023-02-16 21:57 UTC, arufanov requested changes
@cherokee94 lets fix single conversation. Thanks!

2023-02-16 21:57 UTC, arufanov commented on docs/modules/installation/pages/application_configuration.adoc
> +== Configuration file
@cherokee94 important information is follow: use can put any single value to overload. It is not necessary to put the whole yml. For example it can be

```
application:
  paging:
    size: 10

```

to overload items per page. Lets include this info into docs.

2023-02-19 15:16 UTC, cherokee94 commented on docs/modules/installation/pages/application_configuration.adoc
> +== Configuration file
Updated PR

2023-02-19 15:28 UTC, cherokee94 commented
> @cherokee94 see my last commit. It has some minor fixes. I hope you are agree with it.

Ok. But should we list what parameters Axion supports? or leave it for future...? )

2023-02-19 20:04 UTC, arufanov approved these changes
@cherokee94 
* thank!

2023-02-19 20:17 UTC, arufanov commented
@cherokee94 
* i had some problems to resolve conflict. I will close this pr, but fix text at other pr. Check it please.

2023-02-19 20:17 UTC, closed without merging