Installation from sources draft
a5lab/axion pull request #287
Opened 2023-02-16 21:39 UTC by cherokee94

@arufanov maybe we should rename "installation" to "deploy"? we don't install anything...

2023-02-16 22:02 UTC, arufanov requested changes

2023-02-16 22:02 UTC, arufanov commented on docs/modules/installation/pages/installation_from_sources.adoc
> +When building from source files, make sure that all required packages are installed on your system (see xref:installation_prerequisites.adoc[required software]).
@cherokee94 
* java is not enough. See README.md file for details, but is should looks like: 

```
## Windows environment
* download and install java, at least jdk-18 (!! it is included into prereq...)
* create JAVA_HOME environment variable with value C:\Program Files\Java\jdk-19
* exit and run console again to apply environment variables
* download and install maven, at least 3.8.7
* create JAVA_HOME environment variable with value C:\apache-maven-3.8.7
* exit and run console again to apply environment variables
* download and setup nodeJS, at least 18
* install uglifycss by command: npm install -g uglifycss
* install uglifyjs by command: npm install uglify-js -gt
* setup GitHub account and add ssh keys to GitHub profile
* clone repo by command git clone: git@github.com:a5lab/axion.git
* build application by command: mvn clean package -Pdev -Dmaven.test.skip from root folder
* run application by command: mvn spring-boot:run -Pdev from root folder
* open browser with url http://127.0.0.1:8080 to view application

```


in a few works:
* install maven
* install node js
* * install uglifycss by command: npm install -g uglifycss
* install uglifyjs by command: npm install uglify-js -gt
* clone repo
* build application by command: mvn clean package -Pdev -Dmaven.test.skip from root folder
* run application by command: mvn spring-boot:run -Pdev from root folder

Also we should include infor abou 2 profiles: dev for development & production for production:

2023-02-19 14:55 UTC, cherokee94 commented on docs/modules/installation/pages/installation_from_sources.adoc
> +When building from source files, make sure that all required packages are installed on your system (see xref:installation_prerequisites.adoc[required software]).
@arufanov 

1. Updated the prerequisites with maven & uglify packages https://github.com/a5lab/axion/pull/293 
2. Need a call to discuss the profiles

2023-03-02 13:38 UTC, cherokee94 commented on docs/modules/installation/pages/installation_from_sources.adoc
> +When building from source files, make sure that all required packages are installed on your system (see xref:installation_prerequisites.adoc[required software]).
@arufanov info in Installation prerequisites

2023-03-03 22:35 UTC, arufanov approved these changes
@cherokee94 thansk!

2023-03-03 22:36 UTC, merged