Create tests for technologyblip
a5lab/axion pull request #384
Opened 2023-03-23 17:15 UTC by A9afon

Create more tests for technologyblip

2023-03-23 20:54 UTC, arufanov requested changes
@A9afon 
lets discuss and fix.

2023-03-23 20:54 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
> +    final SegmentDto segmentDto = new SegmentDto(10L, null, "My segment title", "My segment description", 1, true);
@A9afon 
* there are 2 approaches to create object

```
    final Radar radar = new Radar();
    radar.setId(10L);
    radar.setTitle("My radar");
    radar.setDescription("My radar description");

    final SegmentDto segmentDto = new SegmentDto(10L, null, "My segment title", "My segment description", 1, true);

``` 

which one we use?

2023-03-23 20:54 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
> +    final Radar radar = new Radar();
@A9afon 
how it is works: radar is fina object, but you able to change it by code radar.setId(10L);

2023-03-31 11:20 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
> +    final SegmentDto segmentDto = new SegmentDto(10L, null, "My segment title", "My segment description", 1, true);
@arufanov 
| Setter | Constructor |
| ------ | --------- |
| **Advantages**: Dependencies can be changed at any time after the object has been created.  | **Advantages**: Cyclic dependency between two objects is not possible |
| **Advantages**: Оbjects of this class become suitable for reconfiguration or re-injection later. | **Advantages**: When using Spring versions 4.3+, you can completely decouple your class from a specific DI framework |
| **Advantages**: Class objects are amenable to reconfiguration and re-injection later. | **Advantages**: Allows you to implement application components as immutable objects and ensure that required dependencies are not null. Сomponents are always returned to client code in a fully initialized state. |
| **Disadvantages**: Possible circular dependency between two objects |  **Disadvantages**: The object becomes less amenable to reconfiguration and re-injection |
| **Сonclusion**: Setters should be used for optional dependency injection. | **Сonclusion**: Constructors are more suitable for mandatory dependencies and when you need immutable objects. |

I recommend using the constructor.

2023-03-31 20:00 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
> +    final SegmentDto segmentDto = new SegmentDto(10L, null, "My segment title", "My segment description", 1, true);
@A9afon 
* there are a few more factors: extension of fields and long constructor created by annotation. Summary: let's discuss by voice and my assumption is settters.

2023-03-31 20:03 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
> +    final Radar radar = new Radar();
@A9afon 
```
    final Radar radar = new Radar();
    radar.setId(10L);
    radar.setTitle("My radar");
    radar.setDescription("My radar description");
    radar = new Radar(); // !!!  Here is error due to final

```

2023-03-31 20:06 UTC, arufanov approved these changes

2023-03-31 20:06 UTC, merged