Refactoring RingCfgControllerTests done
a5lab/axion pull request #402
Opened 2023-04-01 14:04 UTC by A9afon

Refactoring RingCfgControllerTests done

2023-04-01 20:48 UTC, arufanov requested changes

2023-04-01 20:48 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java
> +        ringDto.setTechnologyBlipList(null);
@A9afon 
* should we set null? What is default value?

2023-04-02 17:39 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java
> +        ringDto.setTechnologyBlipList(null);
Shouldn't, I'll fix it.

2023-04-02 19:51 UTC, arufanov approved these changes
@A9afon 
* thanks!

2023-04-02 19:51 UTC, merged