Refactoring SegmentCfgControllerTests done
a5lab/axion pull request #404
Opened 2023-04-01 14:20 UTC by A9afon

Refactoring SegmentCfgControllerTests done

2023-04-01 20:49 UTC, arufanov requested changes

2023-04-01 20:49 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java
> +
@A9afon 
* extra vertical line. Could you remove?

2023-04-01 20:49 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java
> +        segmentDto.setTechnologyBlipList(null);
@A9afon 
* should we set this value? or default value is ok?

2023-04-02 17:39 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java
> +        segmentDto.setTechnologyBlipList(null);
Shouldn't, I'll fix it

2023-04-02 17:41 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java
> +
Yes  i agree

2023-04-02 19:52 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java
> +        segmentDto.setTechnologyBlipList(null);
@A9afon 
* thanks!

2023-04-02 19:52 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/segment/SegmentCfgControllerTests.java
> +
@A9afon 
* thanks!

2023-04-02 19:53 UTC, arufanov approved these changes
@A9afon 
* thanks!

2023-04-02 19:53 UTC, merged