Refactoring TechnologyBlipCfgControllerTests done
a5lab/axion pull request #408
Opened 2023-04-01 14:48 UTC by A9afon

Refactoring TechnologyBlipCfgControllerTests done

2023-04-01 20:53 UTC, arufanov requested changes

2023-04-01 20:53 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
> +    segmentDto.setTechnologyBlipList(null);
@A9afon 
* should we use this setter?

2023-04-01 20:53 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
> +    ringDto.setTechnologyBlipList(null);
@A9afon 
* should we use this setter?

2023-04-02 17:41 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
> +    segmentDto.setTechnologyBlipList(null);
Shouldn't, I'll fix it

2023-04-02 17:41 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/technology_blip/TechnologyBlipCfgControllerTests.java
> +    ringDto.setTechnologyBlipList(null);
Shouldn't, I'll fix it

2023-04-02 19:55 UTC, arufanov approved these changes
@A9afon 
* thanks!

2023-04-02 19:56 UTC, merged