table styles
a5lab/axion pull request #412
Opened 2023-04-01 16:45 UTC by OksanaSidorova

2023-04-01 20:47 UTC, arufanov requested changes

2023-04-01 20:47 UTC, arufanov commented on src/main/resources/static/images/icons/action_delete_axion.svg
@OksanaSidorova 
* should we move actions from images/icons  to images/actions folder? I suppose yes.

2023-04-01 20:47 UTC, arufanov commented on src/main/resources/static/css/application.css
> +.paging-number-wrapper a {
@OksanaSidorova 
* should we move paging & list/table to independent css block similar to " *   Filter styles"

2023-04-02 11:50 UTC, OksanaSidorova commented on src/main/resources/static/images/icons/action_delete_axion.svg
@arufanov ok

2023-04-02 11:51 UTC, OksanaSidorova commented on src/main/resources/static/css/application.css
> +.paging-number-wrapper a {
@arufanov Ok, I'll move

2023-04-02 20:27 UTC, arufanov approved these changes
@OksanaSidorova 
* thanks!

2023-04-02 20:28 UTC, merged