Create Service test for tenant
a5lab/axion pull request #459
Opened 2023-04-09 18:36 UTC by A9afon

Create Service test for tenant

2023-04-09 21:14 UTC, arufanov requested changes

2023-04-09 21:14 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java
> -
@A9afon 
* why do you delete this tests? You can comment it rather that delete. See https://github.com/a5lab/axion/blob/main/src/main/java/com/a5lab/axion/domain/tenant/TenantService.java  you should have tests for all this methods:

```
Collection<TenantDto> findAll();

  Page<TenantDto> findAll(TenantFilter tenantFilter, Pageable pageable);

  Optional<TenantDto> findById(Long id);

  TenantDto save(TenantDto tenantDto);

  void deleteById(Long id);

```

2023-04-09 21:21 UTC, arufanov requested changes

2023-04-09 21:21 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java
> +
@A9afon 
* why do you add extra line?

2023-04-09 21:44 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/tenant/TenantServiceTests.java
> +
@arufanov 
I did not notice. Extra line itself is added when importing the library

2023-04-11 20:31 UTC, arufanov approved these changes

2023-04-11 20:34 UTC, merged