Add radarList
a5lab/axion pull request #603
Opened 2023-05-17 19:46 UTC by A9afon

@arufanov 
Can you check this branch?
If everything is correct, can I fix the tests?
```
[ERROR] Tests run: 177, Failures: 0, Errors: 89, Skipped: 0
[ERROR]   RadarMapperTests.testToDtoAllFields » IllegalState Failed to load ApplicationC...
[ERROR]   RadarMapperTests.testToDtoAllLists » IllegalState Failed to load ApplicationCo...
[ERROR]   RadarMapperTests.testToDtoWithNull » IllegalState Failed to load ApplicationCo...
[ERROR]   RadarMapperTests.testToEntityAllFields » IllegalState Failed to load Applicati...
[ERROR]   RadarMapperTests.testToEntityAllLists » IllegalState Failed to load Applicatio...
[ERROR]   RadarMapperTests.testToEntityWithNull » IllegalState Failed to load Applicatio...
[ERROR]   RadarRepositoryTests.shouldFailOnEmptyDescription » IllegalState Failed to loa...
[ERROR]   RadarRepositoryTests.shouldFailOnEmptyTitle » IllegalState Failed to load Appl...
[ERROR]   RadarRepositoryTests.shouldFailOnNullDescription » IllegalState Failed to load...
[ERROR]   RadarRepositoryTests.shouldFailOnNullTitle » IllegalState Failed to load Appli...
[ERROR]   RadarRepositoryTests.shouldFailOnSecondPrimaryRadar » IllegalState Failed to l...
[ERROR]   RadarRepositoryTests.shouldFailOnWhiteSpaceDescription » IllegalState Failed t...
[ERROR]   RadarRepositoryTests.shouldFailOnWhiteSpaceTitle » IllegalState Failed to load...
[ERROR]   RadarRepositoryTests.shouldSaveRadarWithAllFields » IllegalState Failed to loa...
[ERROR]   RadarServiceTests.shouldDeleteRadar » IllegalState Failed to load ApplicationC...
[ERROR]   RadarServiceTests.shouldFindAllRadars » IllegalState Failed to load Applicatio...
[ERROR]   RadarServiceTests.shouldFindAllRadarsWithFilter » IllegalState Failed to load ...
[ERROR]   RadarServiceTests.shouldFindByIdRadar » IllegalState Failed to load Applicatio...
[ERROR]   RadarServiceTests.shouldFindByPrimaryAndActiveRadars » IllegalState Failed to ...
[ERROR]   RadarServiceTests.shouldFindByPrimaryRadarsIfNotPresent » IllegalState Failed ...
[ERROR]   RadarServiceTests.shouldFindByPrimaryRadarsIfPresent » IllegalState Failed to ...
[ERROR]   RadarServiceTests.shouldSaveRadarDto » IllegalState Failed to load Application...
[ERROR]   RadarTypeMapperTests.testToDtoAllFields » IllegalState Failed to load Applicat...
[ERROR]   RadarTypeMapperTests.testToDtoWithNull » IllegalState Failed to load Applicati...
[ERROR]   RadarTypeMapperTests.testToEntityAllFields » IllegalState Failed to load Appli...
[ERROR]   RadarTypeMapperTests.testToEntityWithNull » IllegalState Failed to load Applic...
[ERROR]   RadarTypeRepositoryTests.shouldSaveRadarWithAllFields » IllegalState Failed to...
[ERROR]   RingMapperTests.testToDtoAllFields » IllegalState Failed to load ApplicationCo...
[ERROR]   RingMapperTests.testToDtoAllLists » IllegalState Failed to load ApplicationCon...
[ERROR]   RingMapperTests.testToDtoWithNull » IllegalState Failed to load ApplicationCon...
[ERROR]   RingMapperTests.testToEntityAllFields » IllegalState Failed to load Applicatio...
[ERROR]   RingRepositoryTests.shouldFailOnEmptyDescription » IllegalState Failed to load...
[ERROR]   RingRepositoryTests.shouldFailOnEmptyTitle » IllegalState Failed to load Appli...
[ERROR]   RingRepositoryTests.shouldFailOnLowerTitle » IllegalState Failed to load Appli...
[ERROR]   RingRepositoryTests.shouldFailOnNullDescription » IllegalState Failed to load ...
[ERROR]   RingRepositoryTests.shouldFailOnNullTitle » IllegalState Failed to load Applic...
[ERROR]   RingRepositoryTests.shouldFailOnWhiteSpaceDescription » IllegalState Failed to...
[ERROR]   RingRepositoryTests.shouldFailOnWhiteSpaceTitle » IllegalState Failed to load ...
[ERROR]   RingRepositoryTests.shouldFindSavedRingById » IllegalState Failed to load Appl...
[ERROR]   RingRepositoryTests.shouldFindSavedRingByTitle » IllegalState Failed to load A...
[ERROR]   RingRepositoryTests.shouldSaveRingWithAllFields » IllegalState Failed to load ...
[ERROR]   RingServiceTests.shouldDeleteRing » IllegalState Failed to load ApplicationCon...
[ERROR]   RingServiceTests.shouldFindAllRings » IllegalState Failed to load ApplicationC...
[ERROR]   RingServiceTests.shouldFindAllRingsWithFilter » IllegalState Failed to load Ap...
[ERROR]   RingServiceTests.shouldFindByIdRing » IllegalState Failed to load ApplicationC...
[ERROR]   RingServiceTests.shouldFindByTitleRing » IllegalState Failed to load Applicati...
[ERROR]   RingServiceTests.shouldSaveRing » IllegalState Failed to load ApplicationConte...
[ERROR]   SegmentMapperTests.testToDtoAllFields » IllegalState Failed to load Applicatio...
[ERROR]   SegmentMapperTests.testToDtoAllLists » IllegalState Failed to load Application...
[ERROR]   SegmentMapperTests.testToDtoWithNull » IllegalState Failed to load Application...
[ERROR]   SegmentMapperTests.testToEntityAllFields » IllegalState Failed to load Applica...
[ERROR]   SegmentMapperTests.testToEntityWithNull » IllegalState Failed to load Applicat...
[ERROR]   SegmentRepositoryTests.shouldFailOnEmptyDescription » IllegalState Failed to l...
[ERROR]   SegmentRepositoryTests.shouldFailOnEmptyTitle » IllegalState Failed to load Ap...
[ERROR]   SegmentRepositoryTests.shouldFailOnNullDescription » IllegalState Failed to lo...
[ERROR]   SegmentRepositoryTests.shouldFailOnNullTitle » IllegalState Failed to load App...
[ERROR]   SegmentRepositoryTests.shouldFailOnWhiteSpaceDescription » IllegalState Failed...
[ERROR]   SegmentRepositoryTests.shouldFailOnWhiteSpaceTitle » IllegalState Failed to lo...
[ERROR]   SegmentRepositoryTests.shouldSaveSegmentWithAllFields » IllegalState Failed to...
[ERROR]   SegmentServiceTests.shouldDeleteSegment » IllegalState Failed to load Applicat...
[ERROR]   SegmentServiceTests.shouldFindAllSegments » IllegalState Failed to load Applic...
[ERROR]   SegmentServiceTests.shouldFindAllSegmentsWithFilter » IllegalState Failed to l...
[ERROR]   SegmentServiceTests.shouldFindByIdSegment » IllegalState Failed to load Applic...
[ERROR]   SegmentServiceTests.shouldFindByTitleSegment » IllegalState Failed to load App...
[ERROR]   SegmentServiceTests.shouldSaveSegment » IllegalState Failed to load Applicatio...
[ERROR]   TechnologyServiceTests.shouldDeleteTechnology » IllegalState Failed to load Ap...
[ERROR]   TechnologyServiceTests.shouldFindAllTechnologies » IllegalState Failed to load...
[ERROR]   TechnologyServiceTests.shouldFindAllTechnologiesWithFilter » IllegalState Fail...
[ERROR]   TechnologyServiceTests.shouldFindByIdTechnology » IllegalState Failed to load ...
[ERROR]   TechnologyServiceTests.shouldFindByTitleTechnology » IllegalState Failed to lo...
[ERROR]   TechnologyServiceTests.shouldSaveTechnology » IllegalState Failed to load Appl...
[ERROR]   TechnologyBlipMapperTests.testToDtoAllFields » IllegalState Failed to load App...
[ERROR]   TechnologyBlipMapperTests.testToEntityAllFields » IllegalState Failed to load ...
[ERROR]   TechnologyBlipMapperTests.testToEntityWithNull » IllegalState Failed to load A...
[ERROR]   TechnologyBlipMapperTests.testToWithNull » IllegalState Failed to load Applica...
[ERROR]   TenantApiIntegrationTests.shouldGetTenants » IllegalState Failed to load Appli...
[ERROR]   TenantCfgIntegrationTests.shouldGetTenants » IllegalState Failed to load Appli...
[ERROR]   TenantMapperTests.testToDtoAllFields » IllegalState Failed to load Application...
[ERROR]   TenantMapperTests.testToDtoWithNull » IllegalState Failed to load ApplicationC...
[ERROR]   TenantMapperTests.testToEntityAllFields » IllegalState Failed to load Applicat...
[ERROR]   TenantMapperTests.testToEntityWithNull » IllegalState Failed to load Applicati...
[ERROR]   TenantRepositoryTests.shouldFailOnEmptyDescription » IllegalState Failed to lo...
[ERROR]   TenantRepositoryTests.shouldFailOnEmptyTitle » IllegalState Failed to load App...
[ERROR]   TenantRepositoryTests.shouldFailOnNullDescription » IllegalState Failed to loa...
[ERROR]   TenantRepositoryTests.shouldFailOnNullTitle » IllegalState Failed to load Appl...
[ERROR]   TenantRepositoryTests [...]

2023-05-17 23:20 UTC, arufanov requested changes

2023-05-17 23:20 UTC, arufanov commented on src/main/java/com/a5lab/axion/domain/radar_type/RadarType.java
> +  @OneToMany(fetch = FetchType.LAZY, mappedBy = "radar_type", cascade = CascadeType.ALL)
@A9afon 
* radar should have @ManytoOne releations. Compare with radar has many rings, and ring belong to one radar.

2023-05-18 13:45 UTC, A9afon commented on src/main/java/com/a5lab/axion/domain/radar_type/RadarType.java
> +  @OneToMany(fetch = FetchType.LAZY, mappedBy = "radar_type", cascade = CascadeType.ALL)
@arufanov 

- But also radarType has many radar. Therefore radarType should have @OneToMany also. Rigth?

2023-05-18 21:27 UTC, arufanov approved these changes

2023-05-18 21:29 UTC, merged