RadarService has been update
a5lab/axion pull request #610
Opened 2023-05-21 16:27 UTC by A9afon

2023-05-24 21:55 UTC, arufanov requested changes

2023-05-24 22:02 UTC, arufanov requested changes

2023-05-24 22:02 UTC, arufanov commented on src/main/java/com/a5lab/axion/domain/radar/RadarCfgController.java
> +    radarFilter.setFilterByPrimary(true);
@A9afon 
* why do you need it? I Suppose that not

2023-05-24 22:02 UTC, arufanov commented on src/main/java/com/a5lab/axion/domain/radar/RadarFilter.java
> +  private boolean filterByPrimary;
@A9afon 
* do yo need constructor? What is init constructor values?

2023-05-24 22:02 UTC, arufanov commented on src/main/java/com/a5lab/axion/domain/radar/RadarServiceImpl.java
> +      if (radarFilter != null && radarFilter.isFilterByPrimary()) {
@A9afon 
* here is error

2023-05-25 15:11 UTC, A9afon commented on src/main/java/com/a5lab/axion/domain/radar/RadarCfgController.java
> +    radarFilter.setFilterByPrimary(true);
OK, it can be removed.

2023-05-25 15:16 UTC, A9afon commented on src/main/java/com/a5lab/axion/domain/radar/RadarServiceImpl.java
> +      if (radarFilter != null && radarFilter.isFilterByPrimary()) {
Can you tell me more?

2023-05-25 21:53 UTC, arufanov commented
@A9afon 
* wee need tests
* we should use jquery instead of javascript
* we should use jquery handler.

2023-05-27 08:17 UTC, A9afon commented
@arufanov 

- Replacing jquery is moved to a separate task.

- Filter testing also needs to be moved to a separate task, since there is currently no solution to this problem.

2023-05-28 19:26 UTC, arufanov approved these changes

2023-05-28 19:28 UTC, merged