Validation test has been implemented
a5lab/axion pull request #658
Opened 2023-06-28 17:36 UTC by A9afon

Validation test has been implemented

2023-06-28 21:04 UTC, arufanov requested changes

2023-06-28 21:04 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/radar/RadarServiceTests.java
> +  void shouldSaveAnyPrimaryRadarDto() throws Exception {
@A9afon 
* I don't understand the idea.

2023-06-28 21:04 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/radar/RadarServiceTests.java
> +  void shouldSaveAnyPrimaryRadarDtoWithAnyRadar() throws Exception {
@A9afon 
* I don't understand the idea.

2023-06-28 21:04 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/radar/RadarCfgControllerTests.java
> +    String content = result.getResponse().getContentAsString();
@A9afon 
* see https://github.com/a5lab/axion/issues/657 can we use attributeHasFieldErrorCode?

2023-06-29 15:13 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/radar/RadarServiceTests.java
> +  void shouldSaveAnyPrimaryRadarDto() throws Exception {
@arufanov 
I didn't see it, my mistake

2023-06-29 15:13 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/radar/RadarServiceTests.java
> +  void shouldSaveAnyPrimaryRadarDtoWithAnyRadar() throws Exception {
@arufanov
I didn't see it, my mistake

2023-07-02 20:17 UTC, arufanov approved these changes

2023-07-02 20:19 UTC, merged