The validate test for ring and segment has been implemented
a5lab/axion pull request #712
Opened 2023-07-22 14:43 UTC by A9afon

PR is ready and waiting for error handling to be added #704 .

2023-07-23 20:21 UTC, arufanov commented
@A9afon 
* Here pr https://github.com/a5lab/axion/pull/713. Could you review it and I will merge it to main.

2023-07-26 13:24 UTC, arufanov requested changes

2023-07-26 13:24 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/ring/RingServiceTests.java
> +    final Radar radar = new Radar();
@A9afon 
* you don't need 2 radars here. Just one active radar and one ring that belong active radar. You should have error while save ring (for example change title).

2023-07-26 13:24 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java
> +        List.of(new ModelError(null, "can not be changed belong active radar", null));
@A9afon 
* could you use real error?

2023-07-26 13:24 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/ring/RingServiceTests.java
> +  void shouldFailToSaveRingToActiveRadarDueToAlreadyBelongActiveRadar() {
@A9afon 
* I am not able to understand use case here .

2023-07-26 20:31 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java
> +        List.of(new ModelError(null, "can not be changed belong active radar", null));
Ok. Should I use this error message "can't be saved for active radar"? If Yes, then we will change title error message to "can not saved for active radar", because see 
```
<ul>
    <li >can&#39;t be saved for active radar</li>
  </ul>
```

2023-07-26 20:34 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/ring/RingCfgControllerTests.java
> +        List.of(new ModelError(null, "can not be changed belong active radar", null));
@A9afon 
* you can use "be saved for active radar" as pattern.
* you can use "can't be saved for active radar" as error, but "can&#39;t be saved for active radar" as pattern search. HTML render transform "'" to &#39 according w3c spec.

2023-08-20 13:57 UTC, arufanov requested changes

2023-08-20 13:57 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/segment/SegmentServiceTests.java
> +    System.out.println(exception.getMessage());
@A9afon 
* could you remove System.out? thanks!

2023-09-04 19:35 UTC, arufanov requested changes

2023-09-04 19:35 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/segment/SegmentServiceTests.java
> +    System.out.println(exception.getMessage());
@A9afon 
* ping

2023-09-05 20:41 UTC, arufanov approved these changes

2023-09-05 20:41 UTC, merged