The tests for filter has been covered
a5lab/axion pull request #725
Opened 2023-07-29 15:12 UTC by A9afon

2023-07-30 18:38 UTC, arufanov requested changes

2023-07-30 18:38 UTC, arufanov commented on src/test/java/com/a5lab/axion/domain/radar/RadarServiceRepositoryTests.java
> +    for (Radar radarAll : radarList) {
@A9afon 
* why do you use: radarAll. Is it better use RadaraList + radar ( or item)?

2023-07-31 11:26 UTC, A9afon commented on src/test/java/com/a5lab/axion/domain/radar/RadarServiceRepositoryTests.java
> +    for (Radar radarAll : radarList) {
@arufanov 
Ok, I'll use RadarList + radar.

2023-08-07 14:40 UTC, arufanov approved these changes

2023-08-07 14:41 UTC, merged